In [1]:
import torch
import numpy as np

In [2]:
x = torch.randn(3, 3 , requires_grad = True)
print(x)
print(x.data)
print(x.grad)
print(x.grad_fn)

tensor([[-0.4386, -0.7335, -1.1962],
        [ 0.1330,  0.9955, -0.2481],
        [ 0.6959, -0.7961, -0.3098]], requires_grad=True)
tensor([[-0.4386, -0.7335, -1.1962],
        [ 0.1330,  0.9955, -0.2481],
        [ 0.6959, -0.7961, -0.3098]])
None
None


In [ ]:
# device

print(  torch.randn(3, device = "cpu").cuda()     )
print(  torch.randn(3, device = "cuda").cpu()     )

print(  torch.randn(3).to(torch.device("cuda"))   )
print(  torch.randn(3, device = "cuda").to("cpu") )

In [10]:
# torch.tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False) -> Tensor
x = np.array([1.1, 2.2, 3.3])
print(x)
print(torch.from_numpy(x))
print(torch.from_numpy(x).type(torch.DoubleTensor))
print(torch.from_numpy(x).type(torch.DoubleTensor).view(3, 1))

In [15]:
layer = torch.nn.Linear(in_features=5, out_features=3, bias=True)
print(layer, '\n')
print(layer.weight, '\n')
print(layer.bias, '\n')
print(layer.training, '\n')

Linear(in_features=5, out_features=3, bias=True) 

Parameter containing:
tensor([[ 0.3802,  0.2179, -0.1130,  0.3050, -0.3253],
        [-0.2766, -0.1968,  0.3709,  0.2948, -0.2054],
        [-0.4037,  0.3592,  0.3534, -0.3526, -0.1566]], requires_grad=True) 

Parameter containing:
tensor([ 0.1439, -0.2230, -0.0157], requires_grad=True) 

True 

